name: Generate Docs

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doxygen and Graphviz
        run: sudo apt install doxygen graphviz -y

      - name: Create docs directory
        run: mkdir -p docs
        
      - name: Run Doxygen for particles
        run: |
          cd particles
          doxygen Doxyfile

      - name: Run Doxygen for signals
        run: |
          cd signals
          doxygen Doxyfile

      - name: Run Doxygen for linksim
        run: |
          cd linksim
          doxygen Doxyfile

      - name: Copy landing page
        run: cp index.html docs/index.html

      - name: Copy signals assests
        run: |
          cp signals/signals.png docs/signals/html/

      - name: Copy linksim assests
        run: |
          cp linksim/ber_curve.png docs/linksim/html/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
